### ISSUE TITLE
在一些主题中会失效

### ISSUE THREAD

**Issue by funcdfs** [tolking/vuepress-plugin-reading-progress#1]
没有用绑定class的算法，例如antdocs主题中就会失效

**Comment by tolking** [comment]
antdocs 将 body 的高度设置为 100% 造成插件获取body的高度出错，因此计算错误失效。
看来需要提供一个配置，用来获取正确html节点高度计算出 readingHeight。
如果你感兴趣欢迎 pull requests

**Comment by funcdfs** [comment]
antdocs作者说：“我不记得有改body为100%，这个插件设计本身就缺那个class”
（我搞算法的，没学过前端）
插件适配以后可能被修复吗？~~~~
（打扰了）

**Comment by funcdfs** [comment]
主要是这个插件很好看，主题也很好看..

**Comment by funcdfs** [comment]
> 主要是这个插件很好看，主题也很好看..

我的能力还不够重写一个。。

**Comment by tolking** [comment]
预计周末更新，增加一个配置，估计十多行代码

**Comment by funcdfs** [comment]
> 预计周末更新，增加一个配置，估计十多行代码

好的，感谢~

**Comment by tolking** [comment]
更新到 1.0.9 应该就能够正常工作了

**Comment by funcdfs** [comment]
> 更新到 1.0.9 应该就能够正常工作了

好的，我试试，感谢~
