### ISSUE TITLE
incompatibility between reading-progress and vuepress-plugin-nprogress

### ISSUE THREAD

**Issue by oupala** [tolking/vuepress-plugin-reading-progress#2]
I had installed *reading progress* VuePress plugin and all was working well. This plugin adds a progress bar while *reading* a page.

[vuepress-plugin-nprogress](https://github.com/vuepress/vuepress-community/tree/master/packages/vuepress-plugin-nprogress) also adds a progress bar while *loading* a page.

It seems that both plugin is incompatible with the other as both try to add a progress bar.

When both are installed, *vuepress-plugin-nprogress* is working while disabling *reading progress*.

See [issue 27](https://github.com/vuepress/vuepress-community/issues/27) for similar issue in *vuepress-plugin-nprogress* repository.

**Comment by tolking** [comment]
nprogress on top of reading-progress while loading a page. both working

**Comment by oupala** [comment]
You're right, I must have been tired yesterday.

Sorry for this false issue...
